Task_1_1_2
SanTsigan/OOP pull request #8
Opened 2024-09-24 05:46 UTC by SanTsigan

2024-10-01 08:12 UTC, shadrina requested changes

2024-10-01 08:12 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/tsyganov/blackjack/Deck.java
> +    public ArrayList<Card> getCards() {
Почему в публичных сигнатурах не надо использовать реализации?

2024-10-01 08:12 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/tsyganov/blackjack/Deck.java
> +    public ArrayList<Card> getCards() {
List<T> - интерфейс. ArrayList<T> - его реализация.

2024-10-01 08:12 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/tsyganov/blackjack/Deck.java
> +    }
Колода же может опустеть?

2024-10-01 08:12 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/tsyganov/blackjack/Deck.java
> +        return (!deck.isEmpty());
Лишние скобки

2024-10-01 08:12 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/tsyganov/blackjack/Deck.java
> +    public void addCards(ArrayList<Card> cards) {
То же самое

2024-10-01 08:12 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/tsyganov/blackjack/Deck.java
> +        return output;
`StringBuilder`

2024-10-01 10:55 UTC, SanTsigan commented on Task_1_1_2/src/main/java/ru/nsu/tsyganov/blackjack/Card.java
> +    private Rank rank;
Для переменных final означает, что однажды присвоенное значение не может быть изменено.

2024-10-01 10:58 UTC, SanTsigan commented on Task_1_1_2/src/main/java/ru/nsu/tsyganov/blackjack/Card.java
> +    public String toString() {
Изначально toString() определен собственно в java.lang.Object. Сам класс Object - это вершина классовой иерархии. Каждый создаваемый класс наследует у него методы.

2024-10-01 10:59 UTC, SanTsigan commented on Task_1_1_2/src/main/java/ru/nsu/tsyganov/blackjack/Deck.java
> +    public ArrayList<Card> getCards() {
Потому что тогда кто нибудь другой, кто захочет использовать наш публичный метод, будет ограничен реализацией и не сможет как-то под себя настроить.

2024-10-14 12:52 UTC, shadrina requested changes

2024-10-14 12:52 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/tsyganov/blackjack/Gender.java
> +    NONE();
Можно опустить скобки и убрать пустой конструктор, все это сгенерируется компилятором по умолчанию

2024-10-14 12:52 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/tsyganov/blackjack/Hand.java
> +    public String toString() {
Выше же был вопрос про `@Override` и правильный на него ответ?

2024-10-14 12:52 UTC, shadrina commented on Task_1_1_2/src/main/java/ru/nsu/tsyganov/blackjack/Suit.java
> +        }
return switch expression please

2024-10-14 12:52 UTC, shadrina commented on Task_1_1_2/src/test/java/ru/nsu/tsyganov/blackjack/MainTest.java
> +        assertEquals("Санёк", player.getName());
Старайся в одном юнит-тесте делать по одному ассерту. Иначе потом распутывать, какой из них упал.

2024-10-15 07:29 UTC, shadrina approved these changes

2024-10-15 08:08 UTC, merged