Task_1_1_3
SanTsigan/OOP pull request #9
Opened 2024-10-01 03:43 UTC by SanTsigan

2024-10-04 04:30 UTC, SanTsigan commented
я не знал что для мягкого дедлайна тоже review надо запрашивать. я по времени уложился просто, а review только сейчас запросил. прошу прощения за недопонимание.

2024-10-15 07:04 UTC, shadrina requested changes

2024-10-15 07:04 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/tsyganov/expressions/ExpressionParser.java
> +import java.util.Stack;
Используй пожалуйста `java.util.Deque`, он поновее и не содержит ненужной синхронизации.

2024-10-15 07:04 UTC, shadrina commented on Task_1_1_3/src/main/java/ru/nsu/tsyganov/expressions/Variable.java
> +            throw new RuntimeException("No variables");
Лучше какой-нибудь более подходящий наследник RuntimeException или свой exception, если подходящего в библиотеке нет (скорее всего есть)

2024-10-15 07:04 UTC, shadrina commented on Task_1_1_3/src/test/java/ru/nsu/tsyganov/expressions/MainTest.java
> +}
Совсем нет тестов посложнее

2024-10-15 07:05 UTC, shadrina commented
В целом, это достаточно близко к апруву

2024-10-29 07:57 UTC, shadrina requested changes
Смотри вкладку Files changed

2025-06-24 02:41 UTC, merged